-- AlterTable
ALTER TABLE "User" ADD COLUMN     "gamesPlayed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gamesWon" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ratingPoints" INTEGER NOT NULL DEFAULT 0;
